ALTER TABLE "invoices"
ADD COLUMN "cgst_amount" DECIMAL(10,2) NOT NULL DEFAULT 0,
ADD COLUMN "sgst_amount" DECIMAL(10,2) NOT NULL DEFAULT 0,
ADD COLUMN "igst_amount" DECIMAL(10,2) NOT NULL DEFAULT 0;
