/* ============================================================
   carrier.service.js — Feature #1: Courier API Integration
   
   Supports: Delhivery, DTDC, BlueDart (live APIs)
   FedEx, DHL (stub — require paid API keys)
   
   Each carrier implements: createShipment, fetchTracking, cancelShipment
   ============================================================ */

'use strict';

const prisma  = require('../config/prisma');
const logger  = require('../utils/logger');
const cache   = require('../utils/cache');
const { fetchJsonWithRetry } = require('../utils/httpRetry');

/* ════════════════════════════════════════════════════════════
   CARRIER CONFIG LOADER
   ════════════════════════════════════════════════════════════ */
function getCarrierConfig(carrier) {
  // Config loaded from environment variables — no DB model needed
  const configs = {
    Delhivery: {
      carrier:     'Delhivery',
      enabled:     !!process.env.DELHIVERY_API_KEY,
      apiKey:      process.env.DELHIVERY_API_KEY,
      apiUrl:      process.env.DELHIVERY_API_URL || 'https://track.delhivery.com',
      warehouseId: process.env.DELHIVERY_WAREHOUSE || 'Primary',
      config:      {
        sellerName:    'Sea Hawk Courier & Cargo',
        sellerAddress: 'Shop 6 & 7, Rao Lal Singh Market',
        sellerCity:    'Gurugram',
        sellerState:   'Haryana',
        sellerPin:     '122015',
      },
    },
    DTDC: {
      carrier:   'DTDC',
      enabled:   !!process.env.DTDC_CUSTOMER_CODE,
      apiKey:    process.env.DTDC_API_KEY,
      apiUrl:    process.env.DTDC_API_URL || 'http://blktapi.dtdc.com',
      config:    { customerCode: process.env.DTDC_CUSTOMER_CODE },
    },
    BlueDart: {
      carrier:   'BlueDart',
      enabled:   !!process.env.BLUEDART_LICENSE_KEY,
      apiKey:    process.env.BLUEDART_LICENSE_KEY,
      apiUrl:    process.env.BLUEDART_API_URL || 'https://apigateway.bluedart.com',
      config:    {
        loginId: process.env.BLUEDART_LOGIN_ID,
        areaCode: process.env.BLUEDART_AREA_CODE || 'Del',
      },
    },
  };
  const cfg = configs[carrier];
  if (!cfg) throw new Error(`Carrier ${carrier} is not supported`);
  if (!cfg.enabled) throw new Error(`Carrier ${carrier} API key not configured. Set env variables.`);
  return cfg;
}

/* ════════════════════════════════════════════════════════════
   DELHIVERY
   Official API: https://developers.delhivery.com
   Required env: DELHIVERY_API_KEY, DELHIVERY_WAREHOUSE
   ════════════════════════════════════════════════════════════ */
const delhivery = {

  async createShipment(data, cfg) {
    const payload = {
      format:          'json',
      data: JSON.stringify({
        shipments: [{
          name:        data.consignee,
          add:         data.deliveryAddress,
          city:        data.deliveryCity,
          state:       data.deliveryState,
          country:     data.deliveryCountry || 'India',
          pin:         data.pin,
          phone:       data.phone || '9999999999',
          order:       data.orderRef || data.awb,
          payment_mode: 'Pre-paid',
          cod_amount:  '0',
          weight:      (data.weightGrams / 1000).toFixed(3),
          shipment_length: data.length || 10,
          shipment_width:  data.width  || 10,
          shipment_height: data.height || 10,
          seller_name:     cfg.config?.sellerName || 'Sea Hawk Courier',
          seller_add:      cfg.config?.sellerAddress || 'Gurugram, Haryana',
          seller_city:     cfg.config?.sellerCity || 'Gurugram',
          seller_state:    cfg.config?.sellerState || 'Haryana',
          seller_pin:      cfg.config?.sellerPin || '122015',
          seller_cust_id:  cfg.config?.customerId || '',
          products_desc:   data.contents || 'Goods',
          hsn_code:        '',
          cod_charges:     '0',
          gift_wrap:       false,
          invoice_value:   String(data.declaredValue || 0),
          waybill:         '', // auto-generated by Delhivery
        }],
        pickup_location: { name: cfg.warehouseId || 'Primary' },
      }),
    };

    const res = await _post(
      `${cfg.apiUrl}/api/cmu/create.json`,
      payload,
      { 'Authorization': `Token ${cfg.apiKey}`, 'Content-Type': 'application/json' },
      'form'
    );

    if (!res.packages?.[0]?.waybill) {
      throw new Error(res.packages?.[0]?.remarks || 'Delhivery AWB generation failed');
    }

    return {
      awb:      res.packages[0].waybill,
      carrier:  'Delhivery',
      trackUrl: `https://www.delhivery.com/track/package/${res.packages[0].waybill}`,
      raw:      res,
    };
  },

  async fetchTracking(awb, cfg) {
    const res = await _get(
      `${cfg.apiUrl}/api/v1/packages/json/?waybill=${awb}`,
      { 'Authorization': `Token ${cfg.apiKey}` }
    );

    const s = res?.ShipmentData?.[0]?.Shipment;
    if (!s) return null;

    const events = (s.Scans || []).map(scan => ({
      status:      mapDelhiveryStatus(scan.ScanDetail?.Scan || ''),
      location:    scan.ScanDetail?.ScannedLocation || '',
      description: scan.ScanDetail?.Instructions || scan.ScanDetail?.Scan || '',
      timestamp:   scan.ScanDetail?.ScanDateTime
                   ? new Date(scan.ScanDetail.ScanDateTime)
                   : new Date(),
      source:      'CARRIER_API',
      rawData:     scan,
    }));

    return {
      status:       mapDelhiveryStatus(s.Status?.Status || ''),
      statusText:   s.Status?.Instructions || s.Status?.Status,
      origin:       s.Origin,
      destination:  s.Destination,
      expectedDate: s.ExpectedDeliveryDate,
      events,
    };
  },

  async cancelShipment(awb, cfg) {
    const res = await _post(
      `${cfg.apiUrl}/api/p/edit`,
      { waybill: awb, cancellation: true },
      { 'Authorization': `Token ${cfg.apiKey}`, 'Content-Type': 'application/json' }
    );
    return res;
  },
};

/* ════════════════════════════════════════════════════════════
   DTDC
   Official API: https://dtdc.com/partner-api/
   Required: DTDC API credentials (partner login)
   ════════════════════════════════════════════════════════════ */
const dtdc = {

  async createShipment(data, cfg) {
    const payload = {
      api_type:    'json',
      request_id:  Date.now().toString(),
      access_token: cfg.apiKey,
      json_input: JSON.stringify([{
        CUST_CODE:     cfg.accountNo,
        ORIGIN_AREA:   'DL',
        CONSIGNEE:     data.consignee,
        DEST_CITY:     data.deliveryCity,
        PINCODE:       data.pin,
        COD_AMOUNT:    '0',
        COMMODITY_VAL: String(data.declaredValue || 0),
        WEIGHT:        String((data.weightGrams / 1000).toFixed(2)),
        ADD1:          data.deliveryAddress?.slice(0, 50) || '',
        ADD2:          data.deliveryAddress?.slice(50, 100) || '',
        TEL_NO:        data.phone || '9999999999',
      }]),
    };

    const res = await _post(
      `${cfg.apiUrl}/secure/shiprequest`,
      payload,
      { 'Content-Type': 'application/json' }
    );

    const pkg = Array.isArray(res) ? res[0] : res;
    if (!pkg?.AWB_NO) throw new Error(pkg?.REASON || 'DTDC AWB generation failed');

    return {
      awb:      pkg.AWB_NO,
      carrier:  'DTDC',
      trackUrl: `https://www.dtdc.in/tracking/tracking.asp?TrkType=awb&strCNNo=${pkg.AWB_NO}`,
      raw:      res,
    };
  },

  async fetchTracking(awb, cfg) {
    const res = await _post(
      `${cfg.apiUrl}/secure/gettracking`,
      { awb_no: awb, access_token: cfg.apiKey },
      { 'Content-Type': 'application/json' }
    );

    if (!res?.shipment_track_activities) return null;

    const events = res.shipment_track_activities.map(e => ({
      status:      mapDTDCStatus(e.act_type || ''),
      location:    e.origin || '',
      description: e.activity || '',
      timestamp:   e.act_time ? new Date(e.act_time) : new Date(),
      source:      'CARRIER_API',
      rawData:     e,
    }));

    return { status: events[0]?.status || 'InTransit', events };
  },

  async cancelShipment(awb, cfg) {
    return await _post(
      `${cfg.apiUrl}/secure/cancelbooking`,
      { awb_no: awb, access_token: cfg.apiKey },
      { 'Content-Type': 'application/json' }
    );
  },
};

/* ════════════════════════════════════════════════════════════
   BLUEDART
   Official API: https://www.bluedart.com/web/guest/api
   Required: BlueDart API license key
   ════════════════════════════════════════════════════════════ */
const bluedart = {

  async createShipment(data, cfg) {
    const payload = {
      Profile: {
        Api_type: 'S',
        LicenceKey: cfg.apiKey,
        LoginID:    cfg.config?.loginId || '',
      },
      Consignee: {
        ConsigneeAddress1: data.deliveryAddress?.slice(0, 50) || '',
        ConsigneeAddress2: data.deliveryAddress?.slice(50) || '',
        ConsigneeAttention: data.consignee,
        ConsigneeCity:      data.deliveryCity,
        ConsigneeMobile:    data.phone || '9999999999',
        ConsigneeName:      data.consignee,
        ConsigneePincode:   data.pin,
        ConsigneeState:     data.deliveryState || '',
      },
      Shipment: {
        ActualWeight:    (data.weightGrams / 1000).toFixed(2),
        CollectableAmount: '0',
        CreditReferenceNo: data.orderRef || '',
        DeclaredValue:   String(data.declaredValue || 0),
        Dimensions: [{
          Breadth: data.width  || 10,
          Height:  data.height || 10,
          Length:  data.length || 10,
          Count:   1,
        }],
        IsDox: data.isDox ? 'Y' : 'N',
        ItemCount: data.pieces || 1,
        PickupDate: `/Date(${Date.now()})/`,
        PickupTime: '1100',
        ProductCode: data.productCode || 'A',
        SpecialInstruction: data.notes || '',
        SubProductCode: '',
      },
      Shipper: {
        OriginArea:   cfg.config?.originArea || 'DEL',
        Shipper:      cfg.config?.shipperCode || '',
        ShipperAddress1: cfg.config?.shipperAddress || 'Gurugram, Haryana',
        ShipperCity:  cfg.config?.shipperCity || 'Gurugram',
        ShipperName:  'Sea Hawk Courier',
        ShipperPincode: cfg.config?.shipperPin || '122015',
      },
    };

    const res = await _post(
      `${cfg.apiUrl}/ShipmentAPI/ShipmentCreation`,
      payload,
      { 'Content-Type': 'application/json' }
    );

    const result = res?.ShipmentCreationResult;
    if (!result?.AWBNo) throw new Error(result?.ErrorMessage || 'BlueDart AWB generation failed');

    return {
      awb:      result.AWBNo,
      carrier:  'BlueDart',
      trackUrl: `https://www.bluedart.com/tracking?trackFor=0&track=awb&trackNo=${result.AWBNo}`,
      raw:      res,
    };
  },

  async fetchTracking(awb, cfg) {
    const res = await _post(
      `${cfg.apiUrl}/TrackingAPI/WaybillTrack`,
      {
        Profile:  { Api_type: 'S', LicenceKey: cfg.apiKey, LoginID: cfg.config?.loginId || '' },
        AWBNo:    awb,
        TrackFor: 0,
      },
      { 'Content-Type': 'application/json' }
    );

    const scans = res?.TrackDetails?.[0]?.TrackNthPacket?.[0]?.TrackPacketSummary;
    if (!scans) return null;

    const events = scans.map(s => ({
      status:      mapBluedartStatus(s.StatusType || ''),
      location:    s.Scanlocation || '',
      description: s.StatusDescription || '',
      timestamp:   s.ScanDate ? new Date(`${s.ScanDate} ${s.ScanTime || ''}`) : new Date(),
      source:      'CARRIER_API',
      rawData:     s,
    }));

    return { status: events[0]?.status || 'InTransit', events };
  },

  async cancelShipment() {
    throw new Error('BlueDart cancellation requires manual process. Contact BlueDart support.');
  },
};

/* ════════════════════════════════════════════════════════════
   FEDEX — Stub (requires FedEx developer account + OAuth2)
   ════════════════════════════════════════════════════════════ */
const fedex = {
  async createShipment() {
    throw new Error('FedEx API integration requires FedEx developer account. See CARRIER-SETUP.md');
  },
  async fetchTracking(awb) {
    // FedEx tracking URLs work without auth for public tracking
    return {
      status:  'Unknown',
      events:  [],
      trackUrl: `https://www.fedex.com/fedextrack/?trknbr=${awb}`,
      message: 'Live FedEx tracking requires FedEx API credentials',
    };
  },
  async cancelShipment() {
    throw new Error('FedEx API integration requires FedEx developer account');
  },
};

/* ════════════════════════════════════════════════════════════
   DHL — Stub (requires DHL Express API credentials)
   ════════════════════════════════════════════════════════════ */
const dhl = {
  async createShipment() {
    throw new Error('DHL API requires DHL Express account. Contact DHL India for API access.');
  },
  async fetchTracking(awb, cfg) {
    if (!cfg?.apiKey) return {
      status:  'Unknown',
      events:  [],
      trackUrl: `https://www.dhl.com/en/express/tracking.html?AWB=${awb}`,
      message: 'DHL API credentials not configured',
    };
    const res = await _get(
      `https://api-eu.dhl.com/track/shipments?trackingNumber=${awb}`,
      { 'DHL-API-Key': cfg.apiKey }
    );
    const events = (res?.shipments?.[0]?.events || []).map(e => ({
      status:      mapDHLStatus(e.typeCode || ''),
      location:    e.location?.address?.addressLocality || '',
      description: e.description || '',
      timestamp:   e.timestamp ? new Date(e.timestamp) : new Date(),
      source:      'CARRIER_API',
      rawData:     e,
    }));
    return { status: events[0]?.status || 'InTransit', events };
  },
  async cancelShipment() {
    throw new Error('DHL shipment cancellation not available via API');
  },
};

/* ════════════════════════════════════════════════════════════
   CARRIER ROUTER
   ════════════════════════════════════════════════════════════ */
const CARRIERS = { Delhivery: delhivery, DTDC: dtdc, BlueDart: bluedart, FedEx: fedex, DHL: dhl };

async function createShipment(carrier, data) {
  const impl = CARRIERS[carrier];
  if (!impl) throw new Error(`Unknown carrier: ${carrier}`);
  const cfg = await getCarrierConfig(carrier);
  logger.info(`Creating shipment via ${carrier} API`, { consignee: data.consignee, pin: data.pin });
  return impl.createShipment(data, cfg);
}

async function fetchTracking(carrier, awb, options = {}) {
  const impl = CARRIERS[carrier];
  if (!impl) throw new Error(`Unknown carrier: ${carrier}`);
  try {
    const upperAwb = String(awb || '').toUpperCase();
    const useCache = !options.bypassCache;
    const cacheKey = `carrier:track:${carrier}:${upperAwb}`;

    if (useCache) {
      const cached = await cache.get(cacheKey);
      if (cached) return cached;
    }

    let cfg;
    try {
      cfg = getCarrierConfig(carrier);
    } catch (err) {
      cfg = { apiUrl: '', apiKey: '', enabled: true, config: {} };
    }
    const tracking = await impl.fetchTracking(awb, cfg);
    if (tracking && useCache) {
      await cache.set(cacheKey, tracking, 300); // 5 minutes
    }
    return tracking;
  } catch (err) {
    logger.warn(`Tracking fetch failed for ${carrier}/${awb}: ${err.message}`);
    return null;
  }
}

async function cancelShipment(carrier, awb) {
  const impl = CARRIERS[carrier];
  if (!impl) throw new Error(`Unknown carrier: ${carrier}`);
  const cfg = await getCarrierConfig(carrier);
  return impl.cancelShipment(awb, cfg);
}

/* ── Persist tracking events to DB ── */
async function syncTrackingEvents(shipmentId, awb, carrier) {
  const tracking = await fetchTracking(carrier, awb, { bypassCache: true });
  if (!tracking?.events?.length) return 0;

  // Get existing events to avoid duplicates
  const existing = await prisma.trackingEvent.findMany({
    where: { shipmentId },
    select: { status: true, timestamp: true },
  });
  const existingSet = new Set(existing.map(e => `${e.status}_${e.timestamp.toISOString()}`));

  const toInsert = tracking.events.filter(e => {
    const key = `${e.status}_${e.timestamp.toISOString()}`;
    return !existingSet.has(key);
  });

  if (toInsert.length === 0) return 0;

  await prisma.trackingEvent.createMany({
    data: toInsert.map(e => ({
      shipmentId,
      awb,
      status:      e.status,
      location:    e.location,
      description: e.description,
      timestamp:   e.timestamp,
      source:      'CARRIER_API',
      rawData:     e.rawData,
    })),
    skipDuplicates: true,
  });

  // Update shipment status with latest
  if (tracking.status) {
    await prisma.shipment.update({
      where: { id: shipmentId },
      data:  { status: tracking.status },
    });
  }

  logger.info(`Synced ${toInsert.length} tracking events for AWB ${awb}`);
  return toInsert.length;
}

/* ════════════════════════════════════════════════════════════
   STATUS MAPPERS
   ════════════════════════════════════════════════════════════ */
function mapDelhiveryStatus(raw) {
  const s = raw.toUpperCase();
  if (s.includes('DELIVER') && !s.includes('OUT')) return 'Delivered';
  if (s.includes('OFD') || s.includes('OUT FOR')) return 'OutForDelivery';
  if (s.includes('TRANSIT') || s.includes('DISPATCH') || s.includes('REACHED')) return 'InTransit';
  if (s.includes('PICK') || s.includes('MANIFEST')) return 'PickedUp';
  if (s.includes('RTO') || s.includes('RETURN')) return 'RTO';
  if (s.includes('FAIL') || s.includes('UNDELIVER')) return 'Failed';
  return 'Booked';
}
function mapDTDCStatus(raw) {
  const s = raw.toUpperCase();
  if (s.includes('DELIVER')) return 'Delivered';
  if (s.includes('OUT FOR')) return 'OutForDelivery';
  if (s.includes('TRANSIT') || s.includes('DISPATCH')) return 'InTransit';
  if (s.includes('PICK') || s.includes('COLLECT')) return 'PickedUp';
  if (s.includes('RTO')) return 'RTO';
  return 'InTransit';
}
function mapBluedartStatus(raw) {
  const s = raw.toUpperCase();
  if (s === 'DL' || s.includes('DELIVER')) return 'Delivered';
  if (s === 'OFD' || s.includes('OUT')) return 'OutForDelivery';
  if (s.includes('TRANSIT') || s.includes('DISPATCH')) return 'InTransit';
  if (s.includes('PICK')) return 'PickedUp';
  if (s.includes('RTO')) return 'RTO';
  return 'InTransit';
}
function mapDHLStatus(raw) {
  const codes = { 'OK': 'Delivered', 'OFD': 'OutForDelivery', 'IT': 'InTransit', 'PU': 'PickedUp' };
  return codes[raw.toUpperCase()] || 'InTransit';
}

/* ════════════════════════════════════════════════════════════
   HTTP HELPERS
   ════════════════════════════════════════════════════════════ */
async function _get(url, headers = {}) {
  return fetchJsonWithRetry(url, { headers }, { attempts: 3, timeoutMs: 10000 });
}

async function _post(url, body, headers = {}, bodyType = 'json') {
  let reqBody, contentType;
  if (bodyType === 'form') {
    reqBody = Object.entries(body).map(([k,v]) => `${encodeURIComponent(k)}=${encodeURIComponent(v)}`).join('&');
    contentType = 'application/x-www-form-urlencoded';
  } else {
    reqBody = JSON.stringify(body);
    contentType = 'application/json';
  }
  return fetchJsonWithRetry(url, {
    method:  'POST',
    headers: { 'Content-Type': contentType, ...headers },
    body:    reqBody,
  }, { attempts: 3, timeoutMs: 12000 });
}

module.exports = {
  createShipment,
  fetchTracking,
  cancelShipment,
  syncTrackingEvents,
  CARRIERS: Object.keys(CARRIERS),
};
