// src/pages/client/ClientInvoicesPage.jsx
import { useState, useEffect } from 'react';
import { Link } from 'react-router-dom';
import api from '../../services/api';
import { PageLoader } from '../../components/ui/Loading';
import { EmptyState } from '../../components/ui/EmptyState';

const fmt = n => `₹${Number(n||0).toLocaleString('en-IN')}`;
const STATUS_COLORS = { DRAFT:'gray', SENT:'blue', PAID:'green', OVERDUE:'red' };

export default function ClientInvoicesPage({ toast }) {
  const [invoices, setInvoices] = useState([]);
  const [loading, setLoading]   = useState(true);
  const [downloadingId, setDownloadingId] = useState(null);

  useEffect(() => {
    api.get('/portal/invoices')
      .then(r => setInvoices(r.data?.invoices || r.data || []))
      .catch(e => toast?.(e.message, 'error'))
      .finally(() => setLoading(false));
  }, []);

  const downloadInvoice = async (invoice) => {
    setDownloadingId(invoice.id);
    try {
      const blob = await api.get(`/portal/invoices/${invoice.id}/pdf`, { responseType: 'blob' });
      const url = window.URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `invoice-${invoice.invoiceNo}.pdf`;
      document.body.appendChild(a);
      a.click();
      a.remove();
      window.URL.revokeObjectURL(url);
    } catch (e) {
      toast?.(e.message || 'Failed to download invoice PDF', 'error');
    } finally {
      setDownloadingId(null);
    }
  };

  if (loading) return <PageLoader />;

  return (
    <div className="min-h-screen bg-gray-50">
      <header className="bg-white border-b px-6 py-4 flex items-center gap-3">
        <Link to="/portal" className="text-gray-400 hover:text-gray-600">← Portal</Link>
        <span className="font-bold text-gray-900">My Invoices</span>
      </header>
      <div className="max-w-4xl mx-auto p-6">
        {invoices.length === 0 ? (
          <EmptyState icon="🧾" title="No invoices yet" message="Invoices will appear here once generated by Sea Hawk." />
        ) : (
          <div className="card p-0 overflow-hidden">
            <table className="w-full text-sm">
              <thead className="bg-gray-50 border-b">
                <tr>
                  {['Invoice No','Period','Total','Status','Download'].map(h =>
                    <th key={h} className="px-4 py-3 text-left text-xs font-semibold text-gray-600 uppercase">{h}</th>
                  )}
                </tr>
              </thead>
              <tbody className="divide-y">
                {invoices.map(inv => (
                  <tr key={inv.id} className="hover:bg-gray-50">
                    <td className="px-4 py-3 font-mono text-xs font-semibold">{inv.invoiceNo}</td>
                    <td className="px-4 py-3 text-gray-600">{inv.fromDate} → {inv.toDate}</td>
                    <td className="px-4 py-3 font-semibold">{fmt(inv.total)}</td>
                    <td className="px-4 py-3">
                      <span className={`badge badge-${STATUS_COLORS[inv.status]||'gray'}`}>{inv.status}</span>
                    </td>
                    <td className="px-4 py-3">
                      <button className="text-blue-600 hover:underline text-xs font-semibold" onClick={() => downloadInvoice(inv)}>
                        {downloadingId === inv.id ? 'Preparing…' : 'Download PDF'}
                      </button>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>
    </div>
  );
}
